---
name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**.go"
      - ".github/workflows/ci.yaml"
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
          fetch-depth: 1

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.5"
          cache-dependency-path: "go.sum"

      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - run: golangci-lint run ./SM83/...

      - run: go test -v ./SM83_tests/...
